### PR TITLE
Use FileProvider and content URIs for attachments

### LINKED ISSUE #16: NotifyDeveloperHandler: FileUriExposedException error
When I try NotifyDeveloperHandler on Android API >=24 then FileUriExposedException is thrown. See details here: https://developer.android.com/reference/android/os/FileUriExposedException

### PR DESCRIPTION
**Pull request by azabost**
Android N and newer doesn't allow sharing files between apps using URIs created with `Uri.fromFile()`. Instead, a `FileProvider` should be used. It allows the receiving application to access the files.

It fixes #16

### CODE REVIEW

File: app/src/main/java/pl/brightinventions/slf4android/Slf4AndroidLogFileProvider.java [hunk 1]
```diff
@@ -0,0 +1,12 @@
+package pl.brightinventions.slf4android;
+
+import android.content.Context;
+import android.support.v4.content.FileProvider;
+
+public class Slf4AndroidLogFileProvider extends FileProvider {
```
Comment (miensol) [inline app/src/main/java/pl/brightinventions/slf4android/Slf4AndroidLogFileProvider.java]: Does this class have to be public? It's probably not a big deal if it is, still I'm curious...

Comment (azabost) [reply app/src/main/java/pl/brightinventions/slf4android/Slf4AndroidLogFileProvider.java]: Yes, it does.
